export type ShapeletFaceType =
  | "face_a"
  | "face_b"
  | "face_c"
  | "face_d"
  | "face_e"
  | "face_f"
  | "face_g"
  | "face_h"
  | "face_i"
  | "face_j"
  | "face_k"
  | "face_l";

export type ShapeletRemainType =
  | "blue_remain"
  | "green_remain"
  | "pink_remain"
  | "purple_remain"
  | "red_remain"
  | "yellow_remain";

export type ShapeletBodyType =
  | "blue_body_squircle"
  | "green_body_squircle"
  | "pink_body_squircle"
  | "purple_body_squircle"
  | "red_body_squircle"
  | "yellow_body_squircle"
  | "blue_body_square"
  | "green_body_square"
  | "pink_body_square"
  | "purple_body_square"
  | "red_body_square"
  | "yellow_body_square"
  | "blue_body_rhombus"
  | "green_body_rhombus"
  | "pink_body_rhombus"
  | "purple_body_rhombus"
  | "red_body_rhombus"
  | "yellow_body_rhombus"
  | "blue_body_circle"
  | "green_body_circle"
  | "pink_body_circle"
  | "purple_body_circle"
  | "red_body_circle"
  | "yellow_body_circle";

export const ShapeletAssetUrls: Record<ShapeletFaceType | ShapeletBodyType | ShapeletRemainType, string> = {
  blue_body_squircle: "./assets/images/bodies/blue_body_squircle.png",
  green_body_squircle: "./assets/images/bodies/green_body_squircle.png",
  pink_body_squircle: "./assets/images/bodies/pink_body_squircle.png",
  purple_body_squircle: "./assets/images/bodies/purple_body_squircle.png",
  red_body_squircle: "./assets/images/bodies/red_body_squircle.png",
  yellow_body_squircle: "./assets/images/bodies/yellow_body_squircle.png",
  blue_body_circle: "./assets/images/bodies/blue_body_circle.png",
  green_body_circle: "./assets/images/bodies/green_body_circle.png",
  pink_body_circle: "./assets/images/bodies/pink_body_circle.png",
  purple_body_circle: "./assets/images/bodies/purple_body_circle.png",
  red_body_circle: "./assets/images/bodies/red_body_circle.png",
  yellow_body_circle: "./assets/images/bodies/yellow_body_circle.png",
  blue_body_rhombus: "./assets/images/bodies/blue_body_rhombus.png",
  green_body_rhombus: "./assets/images/bodies/green_body_rhombus.png",
  pink_body_rhombus: "./assets/images/bodies/pink_body_rhombus.png",
  purple_body_rhombus: "./assets/images/bodies/purple_body_rhombus.png",
  red_body_rhombus: "./assets/images/bodies/red_body_rhombus.png",
  yellow_body_rhombus: "./assets/images/bodies/yellow_body_rhombus.png",
  blue_body_square: "./assets/images/bodies/blue_body_square.png",
  green_body_square: "./assets/images/bodies/green_body_square.png",
  pink_body_square: "./assets/images/bodies/pink_body_square.png",
  purple_body_square: "./assets/images/bodies/purple_body_square.png",
  red_body_square: "./assets/images/bodies/red_body_square.png",
  yellow_body_square: "./assets/images/bodies/yellow_body_square.png",
  face_a: "./assets/images/faces/face_a.png",
  face_b: "./assets/images/faces/face_b.png",
  face_c: "./assets/images/faces/face_c.png",
  face_d: "./assets/images/faces/face_d.png",
  face_e: "./assets/images/faces/face_e.png",
  face_f: "./assets/images/faces/face_f.png",
  face_g: "./assets/images/faces/face_g.png",
  face_h: "./assets/images/faces/face_h.png",
  face_i: "./assets/images/faces/face_i.png",
  face_j: "./assets/images/faces/face_j.png",
  face_k: "./assets/images/faces/face_k.png",
  face_l: "./assets/images/faces/face_l.png",
  blue_remain: "./assets/images/remains/blue_remain.png",
  green_remain: "./assets/images/remains/green_remain.png",
  pink_remain: "./assets/images/remains/pink_remain.png",
  purple_remain: "./assets/images/remains/purple_remain.png",
  red_remain: "./assets/images/remains/red_remain.png",
  yellow_remain: "./assets/images/remains/yellow_remain.png",
};
